### ISSUE TITLE
[Feature] Allow the user to choose a package manager

### ISSUE THREAD

**Issue by CallMeEchoCodes** [palera1n/loader#1]
Yes we all know sileo is the best and should be left as default but some people prefer other package managers (zebra, appinstaller, cydia (gross)). Having options helps with having a more open jailbreak community.

**Comment by BigBoiMan123** [comment]
Afaik sileo nightly is the only package manager that works fully on iOS 15, so this can’t really exist until other package managers are updated for iOS 15.

**Comment by guacaplushy** [comment]
> Afaik sileo nightly is the only package manager that works fully on iOS 15, so this option can’t really exist until other package managers are updated for iOS 15.

this is incorrect; with setuid patch all package managers should work

**Comment by itsnebulalol** [comment]
I was thinking about this, but why not just install it through Sileo? Zebra is already on Procursus

**Comment by llsc12** [comment]
true

**Comment by danni551** [comment]
but saily just works fine

**Comment by DwifteJB** [comment]
MasterMike88 on twitter gives a good reason why saily maybe isn't the best package manager right now.

https://twitter.com/MasterMike88/status/1602195660547268609

**Comment by itsnebulalol** [comment]
implemented
