### ISSUE TITLE
Broken nightly link

### ISSUE THREAD

**Issue by notarun** [palera1n/loader#17]
After e0eeb0299798ba99e88ac5b7afd97c63aa2f3c6f, the build artifacts are not available. This makes the link in the README broken: https://nightly.link/palera1n/loader/workflows/build/main/palera1n.zip. Is the FTP server public, or are there any plans to re-include the build artifacts in the workflow?

**Comment by guacaplushy** [comment]
https://static.palera.in/artifacts/loader/rootful/palera1n.ipa
