### ISSUE TITLE
xcodebuild: error: Could not resolve package dependencies

### ISSUE THREAD

**Issue by MaeThird** [palera1n/loader#5]
after git clone the repo and cd to the loader folder run `make`, it said:

Resolve Package Graph

Updating from https://github.com/tsolomko/SWCompression.git

Updating from https://github.com/tsolomko/BitByteData

Updating from https://github.com/joogps/IrregularGradient

Updating from https://github.com/apple/swift-argument-parser.git

Updating from https://github.com/SDWebImage/SDWebImageswiftui

Updating from https://github.com/SDWebImage/SDWebImage.git

2022-12-18 21:38:02.854 xcodebuild[33037:198577] Writing error result bundle to /var/folders/q9/b3pdps0576q_dr85hr22wtym0000gp/T/ResultBundle_2022-18-12_21-38-0002.xcresult
xcodebuild: error: Could not resolve package dependencies:
  Dependencies could not be resolved because no versions of 'sdwebimage' match the requirement 5.10.0..<6.0.0 and root depends on 'sdwebimageswiftui' 2.0.0..<3.0.0.
'sdwebimageswiftui' >= 2.0.0 practically depends on 'sdwebimage' 5.10.0..<6.0.0 because 'sdwebimageswiftui' 2.2.0 depends on 'sdwebimage' 5.10.0..<6.0.0 and 'sdwebimageswiftui' 2.2.1 depends on 'sdwebimage' 5.10.0..<6.0.0.
'sdwebimageswiftui' {2.0.0..<2.2.0, 2.2.2..<3.0.0} practically depends on 'sdwebimage' 5.10.0..<6.0.0 because 'sdwebimageswiftui' 2.0.2 depends on 'sdwebimage' 5.10.0..<6.0.0 and 'sdwebimageswiftui' 2.1.0 depends on 'sdwebimage' 5.10.0..<6.0.0.
'sdwebimageswiftui' {2.0.0..<2.0.2, 2.0.3..<2.1.0, 2.1.1..<2.2.0, 2.2.2..<3.0.0} practically depends on 'sdwebimage' 5.10.0..<6.0.0 because 'sdwebimageswiftui' 2.0.0 depends on 'sdwebimage' 5.10.0..<6.0.0 and 'sdwebimageswiftui' 2.0.1 depends on 'sdwebimage' 5.10.0..<6.0.0.
'sdwebimageswiftui' {2.0.0, 2.0.3..<2.1.0, 2.1.1..<2.2.0, 2.2.2..<3.0.0} practically depends on 'sdwebimage' 5.10.0..<6.0.0 because no versions of 'sdwebimageswiftui' match the requirement {2.0.3..<2.1.0, 2.1.1..<2.2.0, 2.2.2..<3.0.0} and 'sdwebimageswiftui' 2.0.0 depends on 'sdwebimage' 5.10.0..<6.0.0.

make: *** [package] Error 74

macos : 13.1 (22C65)
xcode:  Version 14.2 (14C18)
any help? Thanks

**Comment by llsc12** [comment]
when i get a chance ill try diagnosing it 👍🏼
