### ISSUE TITLE
Make the background move around similar to Taurine

### ISSUE THREAD

**Issue by CallMeEchoCodes** [palera1n/loader#7]
I just think it would be cool as hell

**Comment by itsnebulalol** [comment]
Issues can be suggestions

**Comment by CallMeEchoCodes** [comment]
> 2. instead of suggesting, how about you make it then make a pr?
because i dont know swift lmao. if i knew how to make it i would have made a pr

**Comment by llsc12** [comment]
just learn swift :trollface:

**Comment by CallMeEchoCodes** [comment]
> just learn swift :trollface:

@llsc12 i really want to but i dont have a mac that can run anything. i might try making a vm

**Comment by llsc12** [comment]
gm now i actually need to learn this but idk where to start
